### PR TITLE
Add support for Services of type ExternalName

### PR DESCRIPTION
**Pull request by twz123**
Such services don't expose clientIPs, ports and the like.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Comment by mohabusama** [comment]
Thanks @twz123

**Comment by mohabusama** [comment]
Released in 0.1-a40 ``registry.opensource.zalan.do/zmon/zmon-agent-core:0.1-a40``

**Pull request merged**
