### PR TITLE
Fix resource parsing

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* `tox.ini`: actually run the doctests
 * Add `n`, `u` units
 * Use `k` instead of `K` for 1000

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Ref: https://github.com/kubernetes/apimachinery/blob/2a7c9300402896b3c073f2f47df85527c94f83a0/pkg/api/resource/suffix.go#L113

**Review by mohabusama — APPROVED** [review]

**Comment by mohabusama** [comment]
👍

**Comment by mohabusama** [comment]
👍

**Comment by vibhory2j** [comment]
👍

**Pull request merged**
