### PR TITLE
Add cluster Environment to kube entities

### LINKED ISSUE #22: Add 'environment' to entities.
In our Kubernetes setup we have the concept of Environments e.g. *Production* and *Test*.
It would be useful to be able to filter on this in entities, similar to what we can do for cluster alias or cluster ID.

### PR DESCRIPTION
**Pull request by mikkeloscar**
Adds cluster environment to kubernetes entities

Fix #22

### CODE REVIEW

**Comment by mohabusama** [comment]
Needs some flake8 ❤️

**Comment by mohabusama** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mohabusama** [comment]
I will add ``delivery.yaml`` to create a new build.

**Pull request merged**
