### PR TITLE
Add namespace to postgresql_database entities

### LINKED ISSUE #82: Add namespace also to postgresql_database entities
The `postgresql_cluster` entities have a "namespace" field, which allows filtering the databases one wants to look at. It would be nice if the same field is also available in the `postgresql_database` field.

As I understand, each database is in exactly one cluster, which has a namespace, so there should be no problem of populating this field too.

### PR DESCRIPTION
**Pull request by ePaul**
This should fix #82, but I didn't test this at all (as I don't have any idea on how to run this).

### CODE REVIEW

**Comment by mohabusama** [comment]
Thanks!
Would it make sense to add `namespace` to `get_postgresql_cluster_members` entities as well?
@Jan-M @avaczi

**Comment by ePaul** [comment]
@mohabusama Sounds useful. I actually thought that would already be happening, as the method has a namespace argument (which is unused, though). I can add this, if wished.

**Comment by mohabusama** [comment]
@ePaul I wouldn't use the passed namespace as it has weird semantic -> None means all namespaces 😉  I would use the pod as it should have a namespace.

**Review by avaczi — APPROVED** [review]

**Review by Jan-M — APPROVED** [review]

**Comment by Jan-M** [comment]
@vetinari

**Comment by vetinari** [comment]
@Jan-M what about the `get_postgresql_cluster_members`?

**Comment by Jan-M** [comment]
Yes please add everywhere. And also the team from teamId if possible.

**Comment by ePaul** [comment]
Hi, I don't really understand what is still needed, I only once looked at the code seven months ago, Python is not one of my strong languages, and I'm currently busy with other high-priority stuff.

Feel free to add on top of my changes to get this finished. (Or, if it is easier, just open a new PR.)

**Comment by vetinari** [comment]
:+1:

**Comment by pitr** [comment]
👍

**Comment by Jan-M** [comment]
:+1:

**Pull request merged**
