### PR TITLE
Isolate postgresql exceptions and enrich sync span errors

### LINKED ISSUE #69: Isolate postgresql exceptions
Isolate and enrich sync OT span with postgresql related exceptions.

### PR DESCRIPTION
**Pull request by mohabusama**
Resolve #69

### CODE REVIEW

**Comment by vetinari** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Comment by mikkeloscar** [comment]
@mohabusama Why is it `team` is a protected field?

**Comment by mohabusama** [comment]
``team`` field prevents replacement of entity, since only team members can change it.

**Pull request merged**
