### PR TITLE
drop unused replicasets

### PR DESCRIPTION
**Pull request by vetinari**
they are also not cleaned up in k8s

### CODE REVIEW

**Comment by vetinari** [comment]
@szuecs please check also

**Comment by szuecs** [comment]
:+1:

**Comment by twz123** [comment]
We are actually using replicaset entities for monitoring stuff. Would it make perhaps more sense to introduce some config option to enable/disable certain entity types, instead of removing support for some of them altogether?

**Comment by szuecs** [comment]
@twz123 What is the reason of using replicaset as entity?
I would go for pods, which we select by label. So kube_pod=foo will find all instances of a foo application. If you want to check state of available replicas, you could also use deployments.

@vetinari do you want to make replicasets an opt-in or opt-out using some flags?

**Comment by mohabusama** [comment]
@twz123 The reason for dropping ``replicaset`` entities is that they can easily explode if ``revisionHistoryLimit`` is not set properly in deployments afaik. So might be useful in the early stage then they will continue growing over time.

If we decided to go with optional flags, then I suggest to have a ``--kubernetes-exclude-entities``, ``ZMON_AGENT_KUBERNETES_EXCLUDE_ENTITIES`` with a comma separated list.

**Comment by szuecs** [comment]
@mohabusama Your suggestion is s great! Let's do that and close this issue with the Opt-Out approach.

**Comment by twz123** [comment]
Great! Thanks guys!

**Comment by Jan-M** [comment]
Sounds like not a ZMON problem, there should be entities for replica sets? after all this is what you need to observe deployments or not?

**Comment by aermakov-zalando** [comment]
I'd keep ZMON entities for entities that exist in Kubernetes so people could use them in checks/alerts. Why drop them?

**Pull request closed without merging**
